### ISSUE TITLE
Traceback on `pkgdev push` (AttributeError: module 'pkgcore.ebuild.atom' has no attribute 'valid_use_flag')

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#502]
When running `pkgdev push` this morning with latest pkgcore stack (9999 ebuilds):
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkgcheck/addons/__init__.py", line 288, in init_addon
    addon = addons_map[cls]
            ~~~~~~~~~~^^^^^
KeyError: <class 'pkgcheck.checks.metadata.IuseCheck'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/pkgdev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgdev/scripts/__init__.py", line 46, in main
    run(os.path.basename(sys.argv[0]))
  File "/usr/lib/python3.11/site-packages/pkgdev/scripts/__init__.py", line 38, in run
    sys.exit(tool())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/cli/tool.py", line 81, in __call__
    ret = self.main()
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgdev/cli.py", line 24, in main
    return super().main()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/cli/tool.py", line 191, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.11/site-packages/snakeoil/cli/tool.py", line 176, in main
    exitstatus = func(self.options, self.out, self.err)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgdev/scripts/pkgdev_push.py", line 55, in _push
    pipe = scan(options.scan_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/api.py", line 44, in scan
    return Pipeline(options)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/__init__.py", line 189, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/addons/__init__.py", line 302, in init_addon
    addon = addons_map[cls] = cls(options, **kwargs)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/metadata.py", line 213, in __init__
    self.valid_use = atom_mod.valid_use_flag.match
                     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgcore.ebuild.atom' has no attribute 'valid_use_flag'
```

**Comment by ferringb** [comment]
Caused by https://github.com/pkgcore/pkgcore/commit/eb6f4edd28d8e25e7ce5aa246f246c51a8bb2211 .
